name: Tweet
on:
  schedule:
    - cron: 55 11 * * *
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    name: tweet
    strategy:
      matrix:
        config:
          - {
              file_dir: tokyo_tech,
              access_token: T2_ACCESS_TOKEN,
              access_token_secret: T2_ACCESS_TOKEN_SECRET,
            }
          - {
              file_dir: keio_univ,
              access_token: KO_ACCESS_TOKEN,
              access_token_secret: KO_ACCESS_TOKEN_SECRET,
            }
          # - {
          #     file_dir: azabu_high,
          #     access_token: AZB_ACCESS_TOKEN,
          #     access_token_secret: AZB_ACCESS_TOKEN_SECRET,
          #   }
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: "x64" # optional x64 or x86. Defaults to x64 if not specified
      - run: pip install requests_oauthlib
      - run: python main.py
        env:
          FILE_DIR: ${{ matrix.config.file_dir }}
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets[matrix.config.access_token] }}
          ACCESS_TOKEN_SECRET: ${{ secrets[matrix.config.access_token_secret] }}
